name: flutter_project_template_firebase
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'
dependencies: 
  another_flushbar: ^1.12.29
  bloc: ^8.1.0
  cloud_firestore: ^4.3.1
  cloud_functions: ^4.0.7
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.1.1
  firebase_auth: ^4.2.2
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  firebase_storage: ^11.0.10
  flutter: 
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_native_splash: ^2.2.16
  flutter_secure_storage: ^9.0.0
  formz: ^0.6.1
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  go_router: ^13.0.0
  google_fonts: ^6.1.0
  import_sorter: ^4.6.0
  injectable: ^2.1.0
  intl: ^0.18.1
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  local_auth: ^2.1.3
  localstorage: ^4.0.0+1
  logger: ^2.0.2+1
  mason: ^0.1.0-dev.40
  package_info_plus: ^5.0.1
  pubspec_dependency_sorter: ^1.0.4
  shared_preferences: ^2.0.15
  
dev_dependencies: 
  build_runner: ^2.3.3
  flutter_lints: ^3.0.1
  flutter_test: 
    sdk: flutter
  injectable_generator: ^2.1.3
  very_good_analysis: ^5.1.0
  
flutter: 
  uses-material-design: true
